# Generated by Django 2.0 on 2017-12-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Author surname')),
                ('lastname', models.CharField(max_length=50, verbose_name='Author lastname')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Book title')),
                ('year', models.PositiveIntegerField(verbose_name='Publication year')),
                ('isbn', models.PositiveIntegerField(blank=True, null=True, verbose_name='ISBN')),
                ('publisher', models.CharField(max_length=50, verbose_name='Publisher')),
                ('place_publish', models.CharField(max_length=50, verbose_name='Place publish')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language',
                 models.CharField(choices=[('CS', 'Czech'), ('DE', 'German'), ('LAT', 'Latin')], default='CS',
                                  max_length=2)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venerated',
                 models.CharField(choices=[('CAT', 'Catholic'), ('ORT', 'Orthodoxy')], default='CAT', max_length=3)),
                ('significant_in', models.CharField(blank=True, max_length=50, null=True,
                                                    verbose_name='Significant in Country, City, ...')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Commentary')),
                ('day', models.PositiveSmallIntegerField(verbose_name='Day')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('name', models.ManyToManyField(related_name='saint_name', to='frontend.Name')),
            ],
        ),
        migrations.CreateModel(
            name='Since',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('century', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Until',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('century', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=50, verbose_name='Page title')),
                ('web_title', models.CharField(max_length=50, verbose_name='Web title')),
                ('url', models.URLField(verbose_name='URL')),
                ('date_visit', models.DateField(verbose_name='Date visit')),
                ('date_citate', models.DateField(verbose_name='Date visit')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='frontend.Author')),
            ],
        ),
        migrations.AddField(
            model_name='saint',
            name='since',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='frontend.Since'),
        ),
        migrations.AddField(
            model_name='saint',
            name='source_book',
            field=models.ManyToManyField(blank=True, to='frontend.Book', verbose_name='Source book'),
        ),
        migrations.AddField(
            model_name='saint',
            name='source_url',
            field=models.ManyToManyField(blank=True, to='frontend.URL', verbose_name='Source book'),
        ),
        migrations.AddField(
            model_name='saint',
            name='until',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='frontend.Until'),
        ),
    ]
