# Generated by Django 2.0 on 2017-12-17 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saint',
            old_name='name',
            new_name='names',
        ),
    ]
